### ISSUE TITLE
setEncoding function not defined

### ISSUE THREAD

**Issue by tseven** [nolanlawson/pouchdb-dump-cli#12] opened 2015-08-24 19:40 UTC
Line 117 of index.js
```
process.stdout.setEncoding('utf8');
```

is causing this error on nodejs v0.12.7.
```
unexpected error
[TypeError: undefined is not a function]
TypeError: undefined is not a function
    at /home/ubuntu/npm/lib/node_modules/pouchdb-dump-cli/index.js:117:22
    at Array.<anonymous> (/home/ubuntu/npm/lib/node_modules/pouchdb-dump-cli/node_modules/lie/lib/unwrap.js:11:21)
    at nextTick (/home/ubuntu/npm/lib/node_modules/pouchdb-dump-cli/node_modules/lie/node_modules/immediate/lib/index.js:61:18)
    at process._tickCallback (node.js:355:11)
```

On nodejs v0.10 the error was more descriptive and mentioned the function "setEncoding" was not defined.

Looking around I found links to similar issues:
https://github.com/voodootikigod/node-serialport/issues/324
https://groups.google.com/forum/#!topic/nodejs/BAv7deMw_48

Simply commenting out line 117 fixes the issue and allows the script to run.

I was originally running the default nodejs and npm packages on Ubuntu 14.04.

I've since manually upgrade nodejs to the latest version v0.12.7.

I hope this helps.

**Comment by nolanlawson** [comment] 2015-08-26 03:27
Hm, it looks like Node removed this method in 0.12. I can't find any documentation about what to do to upgrade, though. :/

**Comment by nolanlawson** [comment] 2015-08-26 03:33
This is really weird. I've tested in Node v0.12.7, Node v0.10.40, and iojs 1.5.0, and I cannot reproduce this issue. I'm on Linux Mint Rebecca. I'm able to dump to stdout just fine; the `setEncoding` line is not throwing an error.

**Comment by Enselic** [comment] 2016-03-08 08:26
process.stdout.setEncoding exists when process.stdout is of type 'tty', but not when it is of type 'fs'.

To test this, first run the following in a terminal

`node -e 'process.stdout.setEncoding("utf8")'`

This will workout fine. Then try to run

`node -e 'process.stdout.setEncoding("utf8")' > foo`

this will fail with "TypeError: process.stdout.setEncoding is not a function". The node code for selecting type of stdout is found in createWritableStdioStream here:
https://github.com/nodejs/node/blob/2ba7baac93d8261d365412b5f000ea9a2de45a04/src/node.js

I have used a later version of node when investigating this but I suspect we see a result of the same issue.

The fix in my case was to replace

`process.stdout.setEncoding('utf8')`
`process.stdout.write(...)`

with 

`process.stdout.write(..., 'utf8')`

**Comment by nolanlawson** [comment] 2016-03-17 19:26
AFAICT this is fixed in the latest release. Please reopen if I'm wrong: https://github.com/nolanlawson/pouchdb-dump-cli/blob/558b9a8515ef49bf1f3756234c7153a282c73585/index.js#L117-L120

**Closed by nolanlawson** 2016-03-17 19:26 UTC
